name: Build-Push Docker Image

on:
  push:
    branches:
      - "develop-new"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.SOLOCODE_USERNAME }}
          password: ${{ secrets.SOLOCODE_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.SOLOCODE_USERNAME }}/wms-backend:latest
      # -
      #   name: Create trigger 
      #   run: |
      #     curl -k --user lieudang:11816ad84e742a5b5a0c980ea9b01c5b6d "https://jenkins.solocode.click/job/wms-backend/build?token=buildtoken"
      - name: Download Jenkins CLI
        run: |
          curl -O http://jenkins.solocode.click/jnlpJars/jenkins-cli.jar
      - name: Trigger Jenkins Build
        run: |
          java -jar jenkins-cli.jar -s http://jenkins.solocode.click/ -auth lieudang:11816ad84e742a5b5a0c980ea9b01c5b6d build wms-backend -s -v