name: Build-Push Docker Image

on:
  push:
    branches:
      - "develop-final"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.SOLOCODE_USERNAME }}
          password: ${{ secrets.SOLOCODE_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.SOLOCODE_USERNAME }}/wms-backend:latest
      -
        name: Create trigger 
        run: |
          curl -k "https://lieudang:11816ad84e742a5b5a0c980ea9b01c5b6d@jenkins.solocode.click/job/wms-backend/build?token=buildtoken"